name: Deploy to AWS EC2
env:
  AWS_REGION: ap-northeast-1
permissions:
  id-token: write
  contents: read
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            APP_ENDPOINT=${{secrets.APP_ENDPOINT}}
            BASE_URL=${{secrets.BASE_URL}}
            APIKEY=${{secrets.APIKEY}}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chad-weblog:latest
